module CustomTests

open System
open Expecto
open Utils
open Expecto.Logging
open Expecto.Logging.Message

// example : https://github.com/haf/expecto/blob/main/Expecto.Sample/Expecto.Sample.fs
// let logger = Log.create "Sample"

// let printingFsCheck =
//     { FsCheckConfig.defaultConfig with
//           receivedArgs =
//               fun _ name no args ->
//                   logger.debugWithBP (
//                       eventX "For {test} {no}, generated {args}"
//                       >> setField "test" name
//                       >> setField "no" no
//                       >> setField "args" args
//                   )
//           maxTest = 128 }

// [<Tests>]
// let testCustom =
//     [ testProperty "addition is commutative"
//       <| fun a b -> a + b = b + a

//       testPropertyWithConfig printingFsCheck "addition is commutative 2"
//       <| fun a b -> a + b = b + a

//       testProperty "addition is not commutative (should fail)"
//       <| fun a b -> a + b = b + -a

//       testPropertyWithConfig FsCheckConfig.defaultConfig "Product is distributive over addition"
//       <|
//       // these parameters are generated by FsCheck
//       fun a b c -> a * (b + c) = a * b + a * c ]
//     |> testList "Custom Tests"
//     |> testSequenced
